import { Navigation } from './components/Navigation';
import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>My first nextjs app</title>
      </head>
      <body>
        <Navigation />
        
        {children}
      </body>
    </html>
  )
}
